# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

steps:
  - group: "Test matrix"
    steps:
      - label: ":linux: Test matrix. Go {{matrix.go_version}}"
        key: test-matrix-lin
        matrix:
          setup:
            go_version:
              - "1.15.8"
              - "1.16.4"
        command:
          - ".buildkite/scripts/test.sh"
        env:
          SETUP_GOLANG_VERSION: "{{matrix.go_version}}"
        agents:
          image: golang:{{matrix.go_version}}
          cpu: "8"
          memory: "4G"
        artifact_paths:
          - "build/junit-*-linux.xml"

      - label: ":windows: Test matrix. Go {{matrix.go_version}}"
        key: test-matrix-win
        matrix:
          setup:
            go_version:
              - "1.15.8"
              - "1.16.4"
        command:
          - ".buildkite/scripts/test.ps1"
        env:
          SETUP_GOLANG_VERSION: "{{matrix.go_version}}"
        agents:
          provider: "gcp"
          image: "family/ci-windows-2022"
        artifact_paths:
          - "build/junit-*-win.xml"

  - label: ":junit: Junit annotate"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "build/junit-*.xml"
    agents:
      provider: "gcp" #junit plugin requires docker
    depends_on:
      - step: "test-matrix-lin"
        allow_failure: true
      - step: "test-matrix-win"
        allow_failure: true
