# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

steps:
  - group: ":linux: Test matrix"
    steps:
      - label: ":linux: Test matrix. Go {{matrix.go_version}}"
        key: test-matrix-lin
        matrix:
          setup:
            go_version:
              - "1.15.8"
              - "1.16.4"
        command:
          - ".buildkite/scripts/test.sh"
        env:
          SETUP_GOLANG_VERSION: "{{matrix.go_version}}"
        agents:
          image: golang:{{matrix.go_version}}
          cpu: "8"
          memory: "4G"

      - label: ":windows: Test matrix. Go {{matrix.go_version}}"
        key: test-matrix-win
        matrix:
          setup:
            go_version:
              - "1.15.8"
              - "1.16.4"
        command:
          - ".buildkite/scripts/test.ps1"
        env:
          SETUP_GOLANG_VERSION: "{{matrix.go_version}}"
        agents:
          provider: "gcp"
          image: "family/ci-windows-2022"
