---
name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.asciidoc'

permissions:
  contents: read

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.15.12', '1.16.4']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Test
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            .ci/test.bat
          else
            .ci/test.sh
          fi
        shell: bash
        env:
          GO_VERSION: ${{ matrix.go-version }}

      - name: Store test results
        if: success() || failure()
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "build/junit-*.xml"
