name: macos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: get go version
      run: |
        gv=$(cat .go-version)
        echo "::set-output name=go::$gv"
      id: version

    - name: install Go
      uses: actions/setup-go@v2
      with:
        go-version: "${{steps.version.outputs.go}}"

    - name: Run test
      run: .ci/test.sh
